### ISSUE TITLE
Error: ENOENT: no such file or directory, open 'data/a15821713c5629b6895370a5c1c59999'

### ISSUE THREAD

**Issue by Ralkage** [jmatzen/quizsail#16]
Tried getting this running locally and it threw an error as soon as I selected and started a test.

```bash
Error: ENOENT: no such file or directory, open 'data/a15821713c5629b6895370a5c1c59999'
    at Object.openSync (fs.js:436:3)
    at Object.writeFileSync (fs.js:1229:35)
    at H:\quizsail\server.js:16:8
    at Layer.handle [as handle_request] (H:\quizsail\node_modules\express\lib\router\layer.js:95:5)
    at next (H:\quizsail\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (H:\quizsail\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (H:\quizsail\node_modules\express\lib\router\layer.js:95:5)
    at H:\quizsail\node_modules\express\lib\router\index.js:281:22
    at param (H:\quizsail\node_modules\express\lib\router\index.js:354:14)
    at param (H:\quizsail\node_modules\express\lib\router\index.js:365:14)
```

It's looking for a `data` folder/directory so my proposed solution would be to add it to this project.

I'll submit a PR for this shortly.

**Edit:** Seen the same closed issues like this one, still think it would be a good idea to add the `data` folder from the get-go to avoid future duplicate issues.

**Comment by jmatzen** [comment]
Yup I've just been waiting for somebody to submit a PR, even though I could just do it directly in github.
